name: Linting workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    needs: [Build]
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Run linting
        run: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
